# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 659872db556f8a49f18d6de0b0c1807e6e7ea090b42986c4dc49a5076f0e27c404f5967ffbc59550377e2579606d78398e86978800c3fc2e0f10327091d8baee

test:
  secret_key_base: 71d70c28d091b77dbe4267f072287e54b1709991b86a41b4428773a0fc41fe013682c91d85b0a369fd922a4f2fdfbac5e890fba68c1fc5fc9a84103fee002345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
